version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${TesloDB}
    container_name: tesloDB
    volumes:
      - ./postgres:/var/lib/postgres/data